# ExtraGore Particle Group Configuration
# ------------------------------------------------------
# This file enables the creation of custom blood particle properties for various entities.
# Begin by uniquely naming each property group to effectively manage different settings.

# Particle Behavior Options:
# - Bounce: The particle will bounce off surfaces like a solid object.
# - Stick: The particle will stick to walls and other surfaces.
# - Magic: Some particles will fall to the ground while the majority will fly up to the sky.
# - None: The particle won't have any special effects.

# Particle Weight Options:
# - Heavy: The particle will sink to the bottom when it's underwater.
# - Light: The particle will float up to the top of the water.

# Particle State Options:
# - Liquid: The particle will get larger during its lifetime.
# - Solid: The particle will remain the same size all the time.

# Color Settings:
# Set an RGB color value to visually distinguish particles for various entities.

# How to Use:
# 1. Define a group with a name, including behavior, weight, state, color and entity values.
# 2. Example:
#    ["Color Group Name"]
#    behavior = Choose from "Stuck", "Bounce" or "None"
#    weight = Choose from "Heavy" or "Light"
#    state = Choose from "Liquid" or "Solid"
#    color = "R,G,B"
#    entities = ["entityID1", "entityID2"]
# 3. You can modify or delete any predefined groups, except for the red group. The red group is non editable and serves only to show you unused entities which are compatible with different color groups.
# 4. Add your custom color groups under an already predefined group, except for the red one.
# 5. Ensure each color group has a unique name and is properly structured.

# Note: Incorrectly formatted lines or unrecognized entity IDs will be ignored.
# ------------------------------------------------------

["Violet Group"]
behavior = "Magic"
weight = "Light"
state = "Liquid"
color = "128,0,128"
entities = ["minecraft:enderman", "minecraft:endermite", "minecraft:phantom", "minecraft:shulker", "minecraft:silverfish", "minecraft:warden", "minecraft:ender_dragon"]

["White Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,255"
entities = ["minecraft:skeleton", "minecraft:ghast", "minecraft:iron_golem", "minecraft:skeleton_horse", "minecraft:snow_golem", "minecraft:stray", "minecraft:vex", "minecraft:wither_skeleton", "minecraft:allay", "minecraft:wither"]

["Green Group"]
behavior = "Stuck"
weight = "Light"
state = "Liquid"
color = "0,255,0"
entities = ["minecraft:cave_spider", "minecraft:creeper", "minecraft:slime", "minecraft:spider", "minecraft:witch"]

["Yellow Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,0"
entities = ["minecraft:blaze", "minecraft:magma_cube", "minecraft:strider"]

["Blue Group"]
behavior = "None"
weight = "Light"
state = "Liquid"
color = "0,0,255"
entities = ["minecraft:squid", "minecraft:elder_guardian", "minecraft:guardian", "minecraft:glow_squid"]

# Auto generated red color group - do not edit. Use this as reference for unused entity IDs.
"255,0,0" = [
    "cataclysm:maledictus",
    "legendary_monsters:overgrown_colossus",
    "cataclysm:coral_golem",
    "alexsmobs:snow_leopard",
    "alexsmobs:endergrade",
    "minecraft:horse",
    "blue_skies:venom_spider",
    "tudigong:tudigong",
    "minecraft:llama",
    "biomeswevegone:man_o_war",
    "alexsmobs:skreecher",
    "cataclysm:ender_guardian",
    "cataclysm:deepling_warlock",
    "minecraft:tadpole",
    "aquamirae:maw",
    "dodosmobs:mecha_dino",
    "alexsmobs:hammerhead_shark",
    "animatedmobsmod:sitting_ender_fiend",
    "alexsmobs:grizzly_bear",
    "legendary_monsters:shulker_mimic",
    "alexsmobs:murmur_head",
    "blue_skies:firefly",
    "faded_conquest_2:vessel_of_calamity",
    "block_factorys_bosses:big_cage_skelly",
    "animatedmobsmod:shade",
    "animatedmobsmod:highlighted_block",
    "minecraft:mooshroom",
    "legendary_monsters:stratling",
    "blue_skies:snow_owl",
    "minecraft:axolotl",
    "dodosmobs:lizardman_guardian",
    "legendary_monsters:ambusher",
    "animatedmobsmod:ender_fiend",
    "fdbosses:chesed_monolith",
    "faded_conquest_2:faded_king",
    "alexsmobs:gorilla",
    "animatedmobsmod:magician_king",
    "quark:crab",
    "blue_skies:starlit_crusher",
    "alexsmobs:cosmic_cod",
    "epicfight:wither_skeleton_minion",
    "alexsmobs:kangaroo",
    "block_factorys_bosses:cage_skelly",
    "blue_skies:polargeist",
    "legendary_monsters:skeloraptor",
    "alexsmobs:hummingbird",
    "block_factorys_bosses:poison_area",
    "blue_skies:stonelet",
    "dreamcaslib:seismic_wave",
    "alexsmobs:crow",
    "blue_skies:shrumpty",
    "alexsmobs:guster",
    "block_factorys_bosses:underworld_knight",
    "faded_conquest_2:blocknight_servant",
    "animatedmobsmod:ice",
    "block_factorys_bosses:big_cage",
    "cataclysm:koboleton",
    "minecraft:chicken",
    "alexsmobs:giant_squid",
    "minecraft:zombie",
    "alexsmobs:emu",
    "blue_skies:frost_spirit",
    "alexsmobs:flutter",
    "minecraft:hoglin",
    "faded_conquest_2:blocknight_leaper",
    "minecraft:zombified_piglin",
    "tudigong:xian_qi",
    "minecraft:sheep",
    "quark:foxhound",
    "alexsmobs:bone_serpent_part",
    "faded_conquest_2:mimic",
    "alexsmobs:raccoon",
    "minecraft:ravager",
    "cataclysm:clawdian",
    "alexsmobs:bone_serpent",
    "cataclysm:drowned_host",
    "blue_skies:charscale_moki",
    "alexsmobs:mudskipper",
    "alexsmobs:crimson_mosquito",
    "faded_conquest_2:blocknight_longarm",
    "wraithon:wraithon",
    "block_factorys_bosses:ice_spike",
    "animatedmobsmod:ender_king_clone",
    "faded_conquest_2:ttphase_2",
    "legendary_monsters:cloud_golem",
    "alexsmobs:jerboa",
    "cataclysm:netherite_ministrosity",
    "faded_conquest_2:agdunegon",
    "alexsmobs:comb_jelly",
    "blue_skies:sliv",
    "cnb:lilytad",
    "fromtheshadows:froglin",
    "block_factorys_bosses:flaming_skeleton_guard_fireball",
    "alexsmobs:enderiophage",
    "alexsmobs:sunbird",
    "fromtheshadows:nehemoth",
    "minecraft:cat",
    "animatedmobsmod:flame",
    "blue_skies:gatekeeper",
    "tcrcore:girl",
    "minecraft:tropical_fish",
    "cataclysm:the_prowler",
    "blue_skies:nested_spider",
    "faded_conquest_2:summoned_creeper",
    "cataclysm:urchinkin",
    "minecraft:zombie_villager",
    "tcrcore:guider",
    "alexsmobs:froststalker",
    "minecraft:giant",
    "faded_conquest_2:radiance_guardian",
    "alexsmobs:lobster",
    "mowziesmobs:lantern",
    "alexsmobs:seagull",
    "animatedmobsmod:facing_key",
    "aquamirae:tortured_soul",
    "blue_skies:artificial_golem",
    "minecraft:husk",
    "bosses_of_mass_destruction:gauntlet",
    "block_factorys_bosses:soul_skeleton",
    "mowziesmobs:umvuthana",
    "minecraft:donkey",
    "gardentrails:silkmoth",
    "mowziesmobs:umvuthana_crane_player",
    "block_factorys_bosses:soul_area",
    "cataclysm:the_leviathan",
    "minecraft:piglin_brute",
    "aquamirae:golden_moth",
    "cataclysm:the_baby_leviathan",
    "cataclysm:deepling_brute",
    "bosses_of_mass_destruction:void_blossom",
    "alexsmobs:frilled_shark",
    "alexsmobs:bald_eagle",
    "cnb:little_grebe",
    "alexsmobs:blobfish",
    "alexsmobs:void_worm",
    "minecraft:parrot",
    "aquamirae:spinefish",
    "cataclysm:scylla",
    "alexsmobs:centipede_head",
    "cataclysm:the_watcher",
    "nightfall_invade:arterius",
    "alexsmobs:banana_slug",
    "cnb:cindershell",
    "faded_conquest_2:meteor",
    "blue_skies:emberback",
    "alexsmobs:bunfungus",
    "minecraft:mule",
    "cataclysm:cindaria",
    "ribbits:ribbit",
    "fdbosses:malkuth",
    "minecraft:vindicator",
    "alexsmobs:flying_fish",
    "block_factorys_bosses:flaming_skeleton_guard_sword",
    "quark:forgotten",
    "cataclysm:nameless_sorcerer",
    "fromtheshadows:cleric",
    "cataclysm:endermaptera",
    "block_factorys_bosses:soul_knight_wither_skeleton",
    "cataclysm:lionfish",
    "cataclysm:coralssus",
    "blue_skies:horizofin_tunid",
    "cnb:minipad",
    "cataclysm:the_harbinger",
    "faded_conquest_2:whirlwind",
    "aquamirae:luminous_jelly",
    "alexsmobs:terrapin",
    "mowziesmobs:bluff",
    "minecraft:pig",
    "alexsmobs:alligator_snapping_turtle",
    "bosses_of_mass_destruction:obsidilith",
    "blue_skies:nyctofly",
    "blue_skies:diophyde_prowler",
    "faded_conquest_2:blocknightfist",
    "blue_skies:infested_swarmer",
    "minecraft:cod",
    "blue_skies:cosmic_fox",
    "alexsmobs:platypus",
    "minecraft:cow",
    "alexsmobs:rocky_roller",
    "block_factorys_bosses:fire_area",
    "alexsmobs:soul_vulture",
    "cnb:yeti",
    "alexsmobs:blue_jay",
    "faded_conquest_2:poison_spike_b",
    "minecraft:salmon",
    "cataclysm:ignis",
    "mowziesmobs:naga",
    "alexsmobs:anteater",
    "alexsmobs:rain_frog",
    "mowziesmobs:ferrous_wroughtnaut",
    "blue_skies:crynocerous",
    "minecraft:rabbit",
    "minecraft:pillager",
    "minecraft:zoglin",
    "alexsmobs:leafcutter_ant",
    "netherexp:ecto_slab",
    "aquamirae:captain_cornelia",
    "faded_conquest_2:blocknight_heavyman",
    "cataclysm:deepling_priest",
    "faded_conquest_2:heiroglyph_room",
    "animatedmobsmod:cursed_tree",
    "faded_conquest_2:summoned_spider",
    "legendary_monsters:skeletosaurus",
    "legendary_monsters:lava_eater",
    "faded_conquest_2:fcdungeon",
    "faded_conquest_2:blocknight_fool",
    "cataclysm:ignited_revenant",
    "alexsmobs:gazelle",
    "minecraft:sniffer",
    "faded_conquest_2:mr_void",
    "monsterexpansion:skrythe",
    "mowziesmobs:umvuthana_follower_player",
    "cataclysm:modern_remnant",
    "cataclysm:symbiocto",
    "alexsmobs:seal",
    "alexsmobs:roadrunner",
    "alexsmobs:laviathan",
    "minecraft:trader_llama",
    "blue_skies:supporter_pet",
    "alexsmobs:maned_wolf",
    "dodosmobs:dead_horn",
    "minecraft:dolphin",
    "faded_conquest_2:blocknight_boot",
    "alexsmobs:gelada_monkey",
    "monsterexpansion:rhyza",
    "animatedmobsmod:trap",
    "blue_skies:azulfo",
    "blue_skies:reindeer",
    "alexsmobs:dropbear",
    "alexsmobs:tiger",
    "faded_conquest_2:poisonspikea",
    "legendary_monsters:haunted_knight",
    "minecraft:bee",
    "alexsmobs:devils_hole_pupfish",
    "minecraft:illusioner",
    "alexsmobs:bison",
    "mowziesmobs:foliaath",
    "mowziesmobs:frostmaw",
    "minecraft:drowned",
    "dodosmobs:bone_chimera",
    "alexsmobs:tusklin",
    "tcrcore:tutorial_golem",
    "alexsmobs:underminer",
    "netherexp:apparition",
    "minecraft:wandering_trader",
    "animatedmobsmod:ender_king_death",
    "biomeswevegone:oddion",
    "faded_conquest_2:puny_juggernaut",
    "blue_skies:grittle_flatfish",
    "legendary_monsters:bomber",
    "animatedmobsmod:black_mamba",
    "cataclysm:netherite_monstrosity",
    "cataclysm:wadjet",
    "blue_skies:spewter",
    "mowziesmobs:umvuthana_raptor",
    "minecraft:pufferfish",
    "minecraft:fox",
    "monsterexpansion:kobeko",
    "mowziesmobs:umvuthana_crane",
    "alexsmobs:warped_toad",
    "blue_skies:seclam",
    "alexsmobs:cockroach",
    "cataclysm:elite_draugr",
    "blue_skies:municipal_monkfish",
    "legendary_monsters:warped_fungussus",
    "cataclysm:deepling_angler",
    "alexsmobs:capuchin_monkey",
    "cnb:cactem",
    "blue_skies:shade_monitor",
    "cataclysm:draugr",
    "minecraft:polar_bear",
    "minecraft:turtle",
    "faded_conquest_2:blocknight_paladin",
    "quark:wraith",
    "alexsmobs:rattlesnake",
    "animatedmobsmod:frozen_skull",
    "legendary_monsters:frostbitten_golem",
    "efn:doppelganger",
    "cataclysm:old_netherite_monstrosity",
    "alexsmobs:potoo",
    "alexsmobs:fly",
    "tcrcore:aine_iris",
    "quark:shiba",
    "alexsmobs:straddler",
    "blue_skies:arachnarch",
    "alexsmobs:sea_bear",
    "mowziesmobs:umvuthana_follower_raptor",
    "cataclysm:ender_golem",
    "alexsmobs:sugar_glider",
    "supplementaries:red_merchant",
    "aquamirae:eel",
    "alexsmobs:orca",
    "blue_skies:summoner",
    "minecraft:bat",
    "alexsmobs:cosmaw",
    "legendary_monsters:knights_armor",
    "legendary_monsters:withered_abomination",
    "blue_skies:alchemist",
    "alexsmobs:skunk",
    "aquamirae:anglerfish",
    "cataclysm:deepling",
    "cnb:end_whale",
    "faded_conquest_2:pbprefight",
    "blue_skies:stardust_ram",
    "alexsmobs:tasmanian_devil",
    "animatedmobsmod:ender_king_damage",
    "cataclysm:ancient_remnant",
    "alexsmobs:stradpole",
    "faded_conquest_2:pbdowned",
    "netherexp:banshee",
    "faded_conquest_2:terrible_ten",
    "minecraft:panda",
    "block_factorys_bosses:sandworm",
    "alexsmobs:moose",
    "alexsmobs:shoebill",
    "alexsmobs:farseer",
    "cataclysm:amethyst_crab",
    "legendary_monsters:mossy_golem",
    "faded_conquest_2:infested",
    "animatedmobsmod:ground_slam",
    "alexsmobs:warped_mosco",
    "blue_skies:jelly_drifter",
    "cataclysm:ancient_ancient_remnant",
    "animatedmobsmod:magician_king_clone",
    "efn:summonedsword",
    "legendary_monsters:haunted_guard",
    "alexsmobs:komodo_dragon",
    "block_factorys_bosses:yeti",
    "aquamirae:maze_mother",
    "cataclysm:ignited_berserker",
    "blue_skies:whistleshell_crab",
    "quark:stoneling",
    "alexsmobs:crocodile",
    "quark:toretoise",
    "netherexp:wisp",
    "fdbosses:fire_malkuth_warrior",
    "alexsmobs:triops",
    "alexsmobs:rhinoceros",
    "cnb:lizard",
    "animatedmobsmod:ender_projectile",
    "alexsmobs:mimicube",
    "faded_conquest_2:calamitycagebreak",
    "faded_conquest_2:toxicrow",
    "dreamcaslib:impact_wave",
    "animatedmobsmod:impact_point",
    "block_factorys_bosses:pile_of_bones",
    "minecraft:frog",
    "legendary_monsters:guard",
    "alexsmobs:mimic_octopus",
    "alexsmobs:void_worm_part",
    "aquamirae:pillagers_patrol",
    "minecraft:evoker",
    "alexsmobs:tarantula_hawk",
    "cnb:sporeling",
    "alexsmobs:cachalot_whale",
    "legendary_monsters:spiky_bug",
    "faded_conquest_2:demon",
    "block_factorys_bosses:cage",
    "cataclysm:hippocamtus",
    "fdbosses:chesed",
    "bosses_of_mass_destruction:lich",
    "alexsmobs:anaconda",
    "mowziesmobs:grottol",
    "faded_conquest_2:faded_kingp_2",
    "legendary_monsters:hovering_hurricane",
    "blue_skies:crogre",
    "legendary_monsters:dune_sentinel",
    "mowziesmobs:baby_foliaath",
    "minecraft:goat",
    "faded_conquest_2:the_plauge_bringerp_2",
    "alexsmobs:mantis_shrimp",
    "netherexp:vessel",
    "animatedmobsmod:snake",
    "legendary_monsters:posessed_paladin",
    "mowziesmobs:umvuthi",
    "monsterexpansion:leivekilth",
    "alexsmobs:toucan",
    "alexsmobs:murmur",
    "faded_conquest_2:the_plauge_bringer",
    "legendary_monsters:chorusling",
    "animatedmobsmod:damage_box",
    "faded_conquest_2:aero_guardian",
    "legendary_monsters:ancient_guardian",
    "alexsmobs:mungus",
    "alexsmobs:caiman",
    "alexsmobs:spectre",
    "cataclysm:kobolediator",
    "blue_skies:armored_frost_spirit",
    "alexsmobs:catfish",
    "minecraft:piglin",
    "alexsmobs:skelewag",
    "epicfight:wither_ghost",
    "animatedmobsmod:ender_king",
    "alexsmobs:elephant",
    "block_factorys_bosses:infernal_dragon",
    "faded_conquest_2:doomharbor_lich",
    "minecraft:zombie_horse",
    "minecraft:camel",
    "cataclysm:royal_draugr",
    "legendary_monsters:endersent",
    "blue_skies:crystal_camel",
    "cataclysm:aptrgangr",
    "fdbosses:ice_malkuth_warrior",
    "netherexp:stampede",
    "minecraft:ocelot",
    "fromtheshadows:bulldrogioth",
    "minecraft:wolf",
    "block_factorys_bosses:dragon_guard_sword"
]
